# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Lucas Moura
tagline:             'Weekly blogly text stuff'
description:         'A space to share some insights about the upcoming. This theme was made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole. 
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Lucas Moura
  url:               https://twitter.com/mourackb
  email:             lmouraccg@gmail.com

# Custom vars
version:             1.0.0
